apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers
  namespace: flux-system
spec:
  interval: 30m
  path: ./infrastructure/overlays/staging/controllers
  prune: true
  wait: true
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infra-sources
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-vars