apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager
  - monitoring
  - ingress-nginx
  - metallb
  - local-path-provisioner
  - hashicorp-vault
  - external-secrets