apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dex-secrets
  namespace: dex
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: dex-secrets
    creationPolicy: Owner
  data:
    - secretKey: ldap-bind-password
      remoteRef:
        key: dex/config
        property: ldap-bind-password
    - secretKey: kubernetes-client-secret
      remoteRef:
        key: dex/config
        property: kubernetes-client-secret
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ldap-ca-cert
  namespace: dex
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: ldap-ca-cert
    creationPolicy: Owner
  data:
    - secretKey: ca.crt
      remoteRef:
        key: dex/config
        property: ldap-ca-cert
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dex-tls
  namespace: dex
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
target:
  name: dex-tls
  template:
    type: kubernetes.io/tls
data:
  - secretKey: tls.crt
    remoteRef:
      key: dex/tls
      property: tls.crt
  - secretKey: tls.key
    remoteRef:
      key: dex/tls
      property: tls.key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dex-config
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: dex-config
    manifest:
      apiVersion: v1
      kind: ConfigMap
  data:
  - secretKey: config.yaml
    remoteRef:
      key: dex/configfile
      property: config.yaml